138 contact at the bottom of the footer
unicef/unicef-innovation-fund pull request #79
Opened 2016-11-11 14:03 UTC by krzysztofp

Added contact field
Updated the echo-html component
Cleaned-up styles
Removed unnecessary firebase-document queries (in favor of using content)
echo-html component change applied to the overlay

2016-11-11 23:25 UTC, mindpal-teams requested changes

2016-11-11 23:25 UTC, sojek commented on app/elements/mdl-footer.html
> +        list-style: none;
Why you set list-style for image selector?

2016-11-11 23:25 UTC, sojek commented on app/elements/mdl-footer.html
> +        -webkit-order: 0;
You don't need prefixes because you have autoprefixer in gulp

2016-11-11 23:25 UTC, sojek commented on app/elements/mdl-footer.html
> +      .footer_area[wide-layout] .sponsol__link {}
You have the same selector above

2016-11-13 00:37 UTC, krzysztofp commented on app/elements/mdl-footer.html
> +        list-style: none;
Oh, I've just re-indented styles in this file, looks like some old style - probably I can delete this one.

2016-11-13 00:40 UTC, krzysztofp commented on app/elements/mdl-footer.html
> +      .footer_area[wide-layout] .sponsol__link {}
I was just re-indenting styles in this file, but let me work on a quick fix for this.

2016-11-13 12:07 UTC, mindpal-teams approved these changes

2016-11-13 12:09 UTC, merged